name: Issue report
description: Report a source issue in LNReader
labels: [Bug]
body:
  - type: dropdown
    id: source
    attributes:
      label: Plugin
      description: Select the plugin associated with the issue.
      options:
        - "ArNovel Id: arnovel"
        - "Azora Id: azora"
        - "dilar tube Id: dilartube"
        - "HizoManga Id: hizomanga"
        - "Kol Novel Id: kolnovel"
        - "Novel4Up Id: novel4up"
        - "Novels Paradise Id: novelsparadise"
        - "Olaoe.cyou Id: olaoe"
        - "Rewayat Club Id: rewayatclub"
        - "Riwyat Id: riwyat"
        - "Sunovels Id: sunovels"
        - "69书吧 Id: 69shu"
        - "69书吧 Id: 69xinshu"
        - "Linovelib Id: linovelib"
        - "Linovelib(繁體) Id: linovelib_tw"
        - "FirstKissNovel Id: 1stkissnovel"
        - "AllNovelFull Id: anf.net"
        - "Arcane Translations Id: arcane"
        - "Archive Of Our Own Id: archiveofourown"
        - "Srank Manga Id: asuralightnovel"
        - "Belle Reservoir Id: bellereservoir"
        - "BestLightNovel Id: BLN"
        - "BoxNovel Id: boxnovel"
        - "Citrus Aurora Id: citrusaurora"
        - "Coral Boutique Id: coralboutique"
        - "CPUnovel Id: cpunovel"
        - "DaoNovel Id: daonovel"
        - "DaoTranslate Id: daotranslate"
        - "Divine Dao Library Id: DDL.com"
        - "Dragon Tea Id: dragontea"
        - "Dream Big Translations Id: dreambigtl"
        - "Dusk Blossoms Id: duskblossoms"
        - "Early Novel Id: earlynovel"
        - "ElloTL Id: ellotl"
        - "Eternalune Id: eternalune"
        - "FanNovel Id: fannovel"
        - "Fans Translations Id: fanstranslations"
        - "Fenrir Translations Id: fenrir"
        - "Foxaholic Id: foxaholic"
        - "Foxteller Id: foxteller"
        - "Faq Wiki Id: FWK.US"
        - "Free Web Novel Id: FWN.com"
        - "Galaxy Translations Id: galaxytranslations"
        - "Genesis Id: genesistudio"
        - "Guavaread Id: guavaread"
        - "Hiraeth Translation Id: hiraethtranslation"
        - "HotNovelPub Id: hotnovelpub"
        - "Ippotranslations Id: ippotranslations"
        - "KnoxT Id: knoxt"
        - "Lib Read Id: libread"
        - "LightNovelCave Id: lightnovelcave"
        - "LightNovelPub Id: lightnovelpub"
        - "LightNovelPub Vip Id: lightnovelpubvip"
        - "Light Novel Updates Id: LightNovelUpdates"
        - "LightNovelWord Id: lightnovelworld"
        - "LightNovelHeaven Id: lnheaven"
        - "LnMTL Id: lnmtl"
        - "Ltnovel Id: ltnovel"
        - "LunarLetters Id: lunarletters"
        - "Meownovel Id: meownovel"
        - "Moonlight Novels Id: moonlightnovel"
        - "MostNovel Id: mostnovel"
        - "MTL-Novel Id: mtl-novel"
        - "MTL Novel Id: mtlnovel"
        - "MTL Reader Id: mtlreader"
        - "MVLEMPYR Id: mvlempyr.com"
        - "MysticalSeries Id: mysticalmerries"
        - "NeoSekai Translations Id: neosekaiTLS"
        - "Nitro Manga Id: nitromanga"
        - "novelsOnline Id: NO.net"
        - "NobleMTL Id: noblemtl"
        - "Novel Bin Id: novelbin"
        - "NovelBuddy.io Id: novelbuddy"
        - "Novel Fire Id: novelfire"
        - "NovelFull Id: novelfull"
        - "Novel Hall Id: novelhall"
        - "NovelMultiverse Id: novelmultiverse"
        - "NovelsKnight Id: novelsknight"
        - "NovelTranslate Id: novelTL"
        - "Novel Updates Id: novelupdates"
        - "Panda Machine Translations Id: pandamtl"
        - "Pastel Tales Id: pasteltales"
        - "PawRead Id: pawread"
        - "Rainofsnow Id: rainofsnow"
        - "Ranobes Id: ranobes"
        - "ReadNovelFull Id: readnovelfull"
        - "Re:Library Id: ReLib"
        - "Requiem Translations Id: requiemtls"
        - "ReadLiteNovel Id: rln.app"
        - "Royal Road Id: royalroad"
        - "Salmon Latte Id: salmonlatte"
        - "Scribble Hub Id: scribblehub"
        - "SleepyTranslations Id: sleeptTLS"
        - "SonicMTL Id: sonicmtl"
        - "StorySeedling Id: storyseedling"
        - "System Translation Id: systemtranslation"
        - "TranslatinOtaku Id: translatinotaku"
        - "Universal Novel Id: universalnovel"
        - "VyNovel Id: vynovel"
        - "Webnovel Id: webnovel"
        - "WebNovelLover Id: webnovelover"
        - "Web Novel Pub Id: webnovelworld"
        - "White Moonlight Novels Id: whitemoonlightnovels"
        - "Wook's Teahouse Id: wooksteahouse"
        - "WordExcerpt Id: wordexcerpt"
        - "WTR-LAB Id: WTRLAB"
        - "Wuxiafox Id: wuxiacity"
        - "Fans MTL Id: wuxiamtl"
        - "Wuxiabox Id: wuxiap"
        - "Wuxia Space Id: wuxiaspace"
        - "WuxiaV Id: wuxiav"
        - "Wuxia World Id: wuxiaworld"
        - "WuxiaWorld.Site Id: wuxiaworld.site"
        - "Zetro Translation Id: zetroTL"
        - "Chireads Id: chireads"
        - "HarkenEliwood Id: harkeneliwood"
        - "KissWood Id: kisswood"
        - "Ligh Novel FR Id: lightnovelfr"
        - "MTL Novel (FR) Id: mtlnovel-fr"
        - "NovelDeGlace Id: noveldeglace"
        - "Novhell Id: novhell"
        - "PhenixScans Id: phenixscans"
        - "Warrior Legend Trad Id: warriorlegendtrad"
        - "WorldNovel Id: worldnovel"
        - "WuxiaLnScantrad Id: wuxialnscantrad"
        - "Xiaowaz Id: xiaowaz"
        - "Baca Light Novel Id: bacalightnovel"
        - "IndoWebNovel Id: IDWN.id"
        - "MeioNovel Id: meionovel"
        - "Risenovel Id: morenovel"
        - "MTL Novel (ID) Id: mtlnovel-id"
        - "NovelBookID Id: novelbookid"
        - "NovelRingan Id: novelringan.com"
        - "SakuraNovel Id: sakura.id"
        - "Sekte Novel Id: sektenovel"
        - "WBNovel Id: wbnovel"
        - "kakuyomu Id: kakuyomu"
        - "Syosetu Id: yomou.syosetu"
        - "Agitoon Id: agit.xyz"
        - "Novelki Id: novelki.pl"
        - "Better Novels Id: betternovels"
        - "Blog do Amon Novels Id: blogdoamonnovels"
        - "Central Novel Id: centralnovel"
        - "Kiniga Id: kiniga"
        - "LaNovels Id: lanovels"
        - "Light Novel Brasil Id: lightnovelbrasil"
        - "MTL Novel (PT) Id: mtlnovel-pt"
        - "Novel Mania Id: novelmania.com.br"
        - "Tsundoku Traduções Id: tsundoku"
        - "Автор Тудей Id: AT"
        - "Bookhamster Id: bookhamster"
        - "Bookriver Id: bookriver"
        - "Erolate Id: erolate"
        - "EzNovels Id: eznovels"
        - "ficbook Id: ficbook"
        - "LitSpace Id: freedlit.space"
        - "Свободный Мир Ранобэ Id: ifreedom"
        - "Jaomix Id: jaomix.ru"
        - "MTL Novel (RU) Id: mtlnovel-ru"
        - "Neobook Id: neobook"
        - "НовелОВХ Id: novelovh"
        - "Ranobes (RU) Id: ranobes-ru"
        - "Renovels Id: ReN"
        - "RanobeLib Id: RLIB"
        - "RanobeHub Id: RNBH.org"
        - "РанобэРФ Id: RNRF"
        - "Rulate Id: rulate"
        - "Ruvers Id: RV"
        - "NovelTL Id: TL"
        - "ТопЛиба Id: TopLiba"
        - "Целлюлоза Id: zelluloza"
        - "AllNovelRead Id: allnovelread"
        - "Hasu Translations Id: HasuTL"
        - "LightNovelDaily Id: lightnoveldaily"
        - "MTL Novel (ES) Id: mtlnovel-es"
        - "Novelas Ligera Id: novelasligera"
        - "Oasis Translations Id: oasistranslations"
        - "Pancho Translations Id: panchotranslations"
        - "ReinoWuxia Id: reinowuxia"
        - "SkyNovels Id: skynovels"
        - "Traducciones Amistosas Id: traducciones"
        - "TuNovelaLigera Id: tunovelaligera"
        - "Yuuki Tls Id: yuukitls"
        - "Novel Lucky Id: novel-lucky"
        - "Novel PDF Id: novelpdf"
        - "Araz Novel Id: azraznovel"
        - "E-KİTAPLAR Id: ekitaplar"
        - "EpikNovel Id: epiknovel"
        - "Kodeks Library Id: kodekslibrary"
        - "NABİ SCANS Id: nabiscans"
        - "Namevt Id: namevt"
        - "Novel oku Id: noveloku"
        - "Novelokutr Id: novelokutr"
        - "NovelTR Id: noveltr"
        - "ThNovels Id: thnovels"
        - "TurkceLightNovels Id: turkcelightnovels"
        - "WebNovelOku Id: webnoveloku"
        - "Смаколики Id: smakolykytl"
        - "Light Novel VN Id: lightnovel.vn"
        - "Hako Id: ln.hako"
        - "Nettruyen Id: nettruyen"
        - "Truyện Chữ Id: truyenchu"
        - "Truyen Conect Id: truyenconect"
        - "Truyện Full Id: truyenfull"
        - "Komga Id: komga"
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: input
    id: lnreader-version
    attributes:
      label: LNReader version
      description: |
        You can find your LNReader version in **More → About**.
      placeholder: |
        Example: "1.1.19"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: |
        You can find this somewhere in your Android settings.
      placeholder: |
        Example: "Android 11"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
          required: true
        - label: I have updated all installed extensions.
          required: true
        - label: If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
          required: true
        - label: I will fill out all of the requested information in this form.
          required: true
