name: Auto Label Issues

on:
  issues:
    types:
      - opened
      - edited

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract plugin names and IDs
        id: extract-plugins
        run: |
          cat ./.github/scripts/keys.json > plugin_map.txt

      - name: Extract the plugin from issue body
        id: parse-issue
        run: |
          # Extract the plugin from the issue body
          BODY=$(echo "Issue body: ${{ github.event.issue.body }}")
          SELECTED_PLUGIN=$(echo "$BODY" | grep "### Plugin" -A 2 | tail -n 1)
          
          echo "SELECTED_PLUGIN=$SELECTED_PLUGIN" >> $GITHUB_ENV

      - name: Determine corresponding label
        id: determine-label
        run: |
          # Map the selected plugin to its ID
          LABEL=$(jq -r ".$SELECTED_PLUGIN" plugin_map.txt)
          echo "LABEL=$LABEL" >> $GITHUB_ENV

      - name: Add label to the issue
        if: env.LABEL != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ env.LABEL }}

      - name: Handle missing label
        if: env.LABEL == ''
        run: echo "No matching label found for the selected plugin."
