name: Auto Label Issues

on:
  issues:
    types:
      - opened
      - edited

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract plugin names and IDs
        id: extract-plugins
        run: |
          cat ./.github/scripts/keys.json > plugin_map.txt

      - name: Extract the plugin from issue body
        id: parse-issue
        run: |
          # Extract the plugin from the issue body
          echo "Issue body: ${{ github.event.issue.body }}"
          SELECTED_PLUGIN=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH" | grep -oP '(?<=- Plugin:\s).*')
          echo $GITHUB_EVENT_PATH
          echo $SELECTED_PLUGIN
          echo "SELECTED_PLUGIN=$SELECTED_PLUGIN" >> $GITHUB_ENV

      - name: Determine corresponding label
        id: determine-label
        run: |
          # Map the selected plugin to its ID
          LABEL=$(jq -r ".$SELECTED_PLUGIN" plugin_map.txt)
          echo "LABEL=$LABEL" >> $GITHUB_ENV

      - name: Add label to the issue
        if: env.LABEL != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ env.LABEL }}

      - name: Handle missing label
        if: env.LABEL == ''
        run: echo "No matching label found for the selected plugin."
