name: Auto Label Issues

on:
  issues:
    types:
      - opened
      - edited

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract plugin names and IDs
        id: extract-plugins
        run: |
          cat ./.github/scripts/keys.json > plugin_map.txt

      - name: Extract the plugin from issue body
        id: parse-issue
        run: |
          # Extract the plugin from the issue body
          
          SELECTED_PLUGIN=$(echo "${{ github.event.issue.body }}" | grep "### Plugin" -A 2 | tail -n 1 | sed 's/[[:space:]]*$//')
          
          echo "SELECTED_PLUGIN=$SELECTED_PLUGIN" >> $GITHUB_ENV

      - name: Determine corresponding label
        id: determine-label
        run: |
          LABELS=$( jq --arg keys "${{ env.SELECTED_PLUGIN }}" '. as $data | $keys | split(",") as $keyList | $keyList[] | . as $key | if $data[$key] != null then $data[$key] else empty end' ./.github/scripts/keys.json | tr -d `\"` )
          echo "LABELS=$LABELS" >> $GITHUB_ENV

      - name: Add label to the issue
        if: env.LABELS != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ env.LABELS }}

      - name: Handle missing label
        if: env.LABELS == ''
        run: echo "No matching label found for the selected plugin."
